import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import api from "./api/index"
import Link from "next/link"


export default function Home(props) {
  return (
    <div className={styles.container}>
      {console.log("props", props)}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {props.popMovieData.results.map((movie, i) => {
        return (
          <Link href={`/movie/${movie.id}`} key={i}><a>{movie.title}</a></Link>)
      })}


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const popularMovieData = await api.popularMovies()
  // const popularTvData = await api.popularTvData
  // const nowPlayingMovies = await api.nowPlayingMovies()

  return {
    props: {
      popMovieData: popularMovieData,
    }
  }
};